name: Main

on:
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: update rust...
      run: rustup update
    - name: build!
      run: cargo build --verbose
    - uses: actions/upload-artifact@v4
      with:
        path: target/release/kicad-wakatime
    - name: ...release!
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: target/release/kicad-wakatime
